version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  mongo:
    image: mongo:7
    container_name: mongo-db-media
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  media-service:
    build: .
    container_name: media-service
    restart: always
    depends_on:
      - mongo
      - minio
    env_file:
      - .env
    ports:
      - "50051:50051"

volumes:
  mongo_data:
  minio_data:
