// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: media-service/media/media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	OriginalName  string                 `protobuf:"bytes,3,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	OwnerId       string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Privacy       string                 `protobuf:"bytes,11,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_media_service_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Media) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *Media) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Media) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Media) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Media) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Media) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Media) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Media) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Media) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Media) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Media) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaRequest) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *UploadMediaRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type GetMediaByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByIDRequest) Reset() {
	*x = GetMediaByIDRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByIDRequest) ProtoMessage() {}

func (x *GetMediaByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMediaByIDRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetMediaByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMediaByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByIDResponse) Reset() {
	*x = GetMediaByIDResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByIDResponse) ProtoMessage() {}

func (x *GetMediaByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByIDResponse.ProtoReflect.Descriptor instead.
func (*GetMediaByIDResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetMediaByIDResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type ListMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        map[string]string      `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaRequest) Reset() {
	*x = ListMediaRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaRequest) ProtoMessage() {}

func (x *ListMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaRequest.ProtoReflect.Descriptor instead.
func (*ListMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{5}
}

func (x *ListMediaRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListMediaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMediaRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*Media               `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaResponse) Reset() {
	*x = ListMediaResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaResponse) ProtoMessage() {}

func (x *ListMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaResponse.ProtoReflect.Descriptor instead.
func (*ListMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{6}
}

func (x *ListMediaResponse) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMediaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteMediaRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaRequest) Reset() {
	*x = UpdateMediaRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaRequest) ProtoMessage() {}

func (x *UpdateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMediaRequest) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type UpdateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaResponse) Reset() {
	*x = UpdateMediaResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaResponse) ProtoMessage() {}

func (x *UpdateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaResponse.ProtoReflect.Descriptor instead.
func (*UpdateMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type GetByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByOwnerRequest) Reset() {
	*x = GetByOwnerRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByOwnerRequest) ProtoMessage() {}

func (x *GetByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{11}
}

func (x *GetByOwnerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetByOwnerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetByOwnerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*Media               `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByOwnerResponse) Reset() {
	*x = GetByOwnerResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByOwnerResponse) ProtoMessage() {}

func (x *GetByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{12}
}

func (x *GetByOwnerResponse) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

type GetByTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTagsRequest) Reset() {
	*x = GetByTagsRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTagsRequest) ProtoMessage() {}

func (x *GetByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTagsRequest.ProtoReflect.Descriptor instead.
func (*GetByTagsRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{13}
}

func (x *GetByTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetByTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetByTagsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetByTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*Media               `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTagsResponse) Reset() {
	*x = GetByTagsResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTagsResponse) ProtoMessage() {}

func (x *GetByTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTagsResponse.ProtoReflect.Descriptor instead.
func (*GetByTagsResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{14}
}

func (x *GetByTagsResponse) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

type GetExpiredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpiredRequest) Reset() {
	*x = GetExpiredRequest{}
	mi := &file_media_service_media_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiredRequest) ProtoMessage() {}

func (x *GetExpiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiredRequest.ProtoReflect.Descriptor instead.
func (*GetExpiredRequest) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{15}
}

type GetExpiredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*Media               `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpiredResponse) Reset() {
	*x = GetExpiredResponse{}
	mi := &file_media_service_media_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiredResponse) ProtoMessage() {}

func (x *GetExpiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_media_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiredResponse.ProtoReflect.Descriptor instead.
func (*GetExpiredResponse) Descriptor() ([]byte, []int) {
	return file_media_service_media_media_proto_rawDescGZIP(), []int{16}
}

func (x *GetExpiredResponse) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

var File_media_service_media_media_proto protoreflect.FileDescriptor

const file_media_service_media_media_proto_rawDesc = "" +
	"\n" +
	"\x1fmedia-service/media/media.proto\x12\x05media\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x05\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12#\n" +
	"\roriginal_name\x18\x03 \x01(\tR\foriginalName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1c\n" +
	"\tthumbnail\x18\a \x01(\tR\tthumbnail\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x126\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1a.media.Media.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aprivacy\x18\v \x01(\tR\aprivacy\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x12UploadMediaRequest\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\"9\n" +
	"\x13UploadMediaResponse\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"%\n" +
	"\x13GetMediaByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x14GetMediaByIDResponse\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"\xb8\x01\n" +
	"\x10ListMediaRequest\x12;\n" +
	"\x06filter\x18\x01 \x03(\v2#.media.ListMediaRequest.FilterEntryR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x11ListMediaResponse\x12$\n" +
	"\x06medias\x18\x01 \x03(\v2\f.media.MediaR\x06medias\":\n" +
	"\x12DeleteMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x12UpdateMediaRequest\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"9\n" +
	"\x13UpdateMediaResponse\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"\\\n" +
	"\x11GetByOwnerRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\":\n" +
	"\x12GetByOwnerResponse\x12$\n" +
	"\x06medias\x18\x01 \x03(\v2\f.media.MediaR\x06medias\"T\n" +
	"\x10GetByTagsRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"9\n" +
	"\x11GetByTagsResponse\x12$\n" +
	"\x06medias\x18\x01 \x03(\v2\f.media.MediaR\x06medias\"\x13\n" +
	"\x11GetExpiredRequest\":\n" +
	"\x12GetExpiredResponse\x12$\n" +
	"\x06medias\x18\x01 \x03(\v2\f.media.MediaR\x06medias2\xaf\x04\n" +
	"\fMediaService\x12D\n" +
	"\vUploadMedia\x12\x19.media.UploadMediaRequest\x1a\x1a.media.UploadMediaResponse\x12G\n" +
	"\fGetMediaByID\x12\x1a.media.GetMediaByIDRequest\x1a\x1b.media.GetMediaByIDResponse\x12>\n" +
	"\tListMedia\x12\x17.media.ListMediaRequest\x1a\x18.media.ListMediaResponse\x12D\n" +
	"\vDeleteMedia\x12\x19.media.DeleteMediaRequest\x1a\x1a.media.DeleteMediaResponse\x12D\n" +
	"\vUpdateMedia\x12\x19.media.UpdateMediaRequest\x1a\x1a.media.UpdateMediaResponse\x12A\n" +
	"\n" +
	"GetByOwner\x12\x18.media.GetByOwnerRequest\x1a\x19.media.GetByOwnerResponse\x12>\n" +
	"\tGetByTags\x12\x17.media.GetByTagsRequest\x1a\x18.media.GetByTagsResponse\x12A\n" +
	"\n" +
	"GetExpired\x12\x18.media.GetExpiredRequest\x1a\x19.media.GetExpiredResponseB\n" +
	"Z\b/mediapbb\x06proto3"

var (
	file_media_service_media_media_proto_rawDescOnce sync.Once
	file_media_service_media_media_proto_rawDescData []byte
)

func file_media_service_media_media_proto_rawDescGZIP() []byte {
	file_media_service_media_media_proto_rawDescOnce.Do(func() {
		file_media_service_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_service_media_media_proto_rawDesc), len(file_media_service_media_media_proto_rawDesc)))
	})
	return file_media_service_media_media_proto_rawDescData
}

var file_media_service_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_media_service_media_media_proto_goTypes = []any{
	(*Media)(nil),                 // 0: media.Media
	(*UploadMediaRequest)(nil),    // 1: media.UploadMediaRequest
	(*UploadMediaResponse)(nil),   // 2: media.UploadMediaResponse
	(*GetMediaByIDRequest)(nil),   // 3: media.GetMediaByIDRequest
	(*GetMediaByIDResponse)(nil),  // 4: media.GetMediaByIDResponse
	(*ListMediaRequest)(nil),      // 5: media.ListMediaRequest
	(*ListMediaResponse)(nil),     // 6: media.ListMediaResponse
	(*DeleteMediaRequest)(nil),    // 7: media.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),   // 8: media.DeleteMediaResponse
	(*UpdateMediaRequest)(nil),    // 9: media.UpdateMediaRequest
	(*UpdateMediaResponse)(nil),   // 10: media.UpdateMediaResponse
	(*GetByOwnerRequest)(nil),     // 11: media.GetByOwnerRequest
	(*GetByOwnerResponse)(nil),    // 12: media.GetByOwnerResponse
	(*GetByTagsRequest)(nil),      // 13: media.GetByTagsRequest
	(*GetByTagsResponse)(nil),     // 14: media.GetByTagsResponse
	(*GetExpiredRequest)(nil),     // 15: media.GetExpiredRequest
	(*GetExpiredResponse)(nil),    // 16: media.GetExpiredResponse
	nil,                           // 17: media.Media.MetadataEntry
	nil,                           // 18: media.ListMediaRequest.FilterEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_media_service_media_media_proto_depIdxs = []int32{
	17, // 0: media.Media.metadata:type_name -> media.Media.MetadataEntry
	19, // 1: media.Media.expires_at:type_name -> google.protobuf.Timestamp
	19, // 2: media.Media.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: media.Media.updated_at:type_name -> google.protobuf.Timestamp
	19, // 4: media.Media.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 5: media.UploadMediaRequest.media:type_name -> media.Media
	0,  // 6: media.UploadMediaResponse.media:type_name -> media.Media
	0,  // 7: media.GetMediaByIDResponse.media:type_name -> media.Media
	18, // 8: media.ListMediaRequest.filter:type_name -> media.ListMediaRequest.FilterEntry
	0,  // 9: media.ListMediaResponse.medias:type_name -> media.Media
	0,  // 10: media.UpdateMediaRequest.media:type_name -> media.Media
	0,  // 11: media.UpdateMediaResponse.media:type_name -> media.Media
	0,  // 12: media.GetByOwnerResponse.medias:type_name -> media.Media
	0,  // 13: media.GetByTagsResponse.medias:type_name -> media.Media
	0,  // 14: media.GetExpiredResponse.medias:type_name -> media.Media
	1,  // 15: media.MediaService.UploadMedia:input_type -> media.UploadMediaRequest
	3,  // 16: media.MediaService.GetMediaByID:input_type -> media.GetMediaByIDRequest
	5,  // 17: media.MediaService.ListMedia:input_type -> media.ListMediaRequest
	7,  // 18: media.MediaService.DeleteMedia:input_type -> media.DeleteMediaRequest
	9,  // 19: media.MediaService.UpdateMedia:input_type -> media.UpdateMediaRequest
	11, // 20: media.MediaService.GetByOwner:input_type -> media.GetByOwnerRequest
	13, // 21: media.MediaService.GetByTags:input_type -> media.GetByTagsRequest
	15, // 22: media.MediaService.GetExpired:input_type -> media.GetExpiredRequest
	2,  // 23: media.MediaService.UploadMedia:output_type -> media.UploadMediaResponse
	4,  // 24: media.MediaService.GetMediaByID:output_type -> media.GetMediaByIDResponse
	6,  // 25: media.MediaService.ListMedia:output_type -> media.ListMediaResponse
	8,  // 26: media.MediaService.DeleteMedia:output_type -> media.DeleteMediaResponse
	10, // 27: media.MediaService.UpdateMedia:output_type -> media.UpdateMediaResponse
	12, // 28: media.MediaService.GetByOwner:output_type -> media.GetByOwnerResponse
	14, // 29: media.MediaService.GetByTags:output_type -> media.GetByTagsResponse
	16, // 30: media.MediaService.GetExpired:output_type -> media.GetExpiredResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_media_service_media_media_proto_init() }
func file_media_service_media_media_proto_init() {
	if File_media_service_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_service_media_media_proto_rawDesc), len(file_media_service_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_service_media_media_proto_goTypes,
		DependencyIndexes: file_media_service_media_media_proto_depIdxs,
		MessageInfos:      file_media_service_media_media_proto_msgTypes,
	}.Build()
	File_media_service_media_media_proto = out.File
	file_media_service_media_media_proto_goTypes = nil
	file_media_service_media_media_proto_depIdxs = nil
}
